require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClowdsController do

  # This should return the minimal set of attributes required to create a valid
  # Clowd. As you add validations to Clowd, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClowdsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all clowds as @clowds" do
      clowd = Clowd.create! valid_attributes
      get :index, {}, valid_session
      assigns(:clowds).should eq([clowd])
    end
  end

  describe "GET show" do
    it "assigns the requested clowd as @clowd" do
      clowd = Clowd.create! valid_attributes
      get :show, {:id => clowd.to_param}, valid_session
      assigns(:clowd).should eq(clowd)
    end
  end

  describe "GET new" do
    it "assigns a new clowd as @clowd" do
      get :new, {}, valid_session
      assigns(:clowd).should be_a_new(Clowd)
    end
  end

  describe "GET edit" do
    it "assigns the requested clowd as @clowd" do
      clowd = Clowd.create! valid_attributes
      get :edit, {:id => clowd.to_param}, valid_session
      assigns(:clowd).should eq(clowd)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Clowd" do
        expect {
          post :create, {:clowd => valid_attributes}, valid_session
        }.to change(Clowd, :count).by(1)
      end

      it "assigns a newly created clowd as @clowd" do
        post :create, {:clowd => valid_attributes}, valid_session
        assigns(:clowd).should be_a(Clowd)
        assigns(:clowd).should be_persisted
      end

      it "redirects to the created clowd" do
        post :create, {:clowd => valid_attributes}, valid_session
        response.should redirect_to(Clowd.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved clowd as @clowd" do
        # Trigger the behavior that occurs when invalid params are submitted
        Clowd.any_instance.stub(:save).and_return(false)
        post :create, {:clowd => {}}, valid_session
        assigns(:clowd).should be_a_new(Clowd)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Clowd.any_instance.stub(:save).and_return(false)
        post :create, {:clowd => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested clowd" do
        clowd = Clowd.create! valid_attributes
        # Assuming there are no other clowds in the database, this
        # specifies that the Clowd created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Clowd.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => clowd.to_param, :clowd => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested clowd as @clowd" do
        clowd = Clowd.create! valid_attributes
        put :update, {:id => clowd.to_param, :clowd => valid_attributes}, valid_session
        assigns(:clowd).should eq(clowd)
      end

      it "redirects to the clowd" do
        clowd = Clowd.create! valid_attributes
        put :update, {:id => clowd.to_param, :clowd => valid_attributes}, valid_session
        response.should redirect_to(clowd)
      end
    end

    describe "with invalid params" do
      it "assigns the clowd as @clowd" do
        clowd = Clowd.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Clowd.any_instance.stub(:save).and_return(false)
        put :update, {:id => clowd.to_param, :clowd => {}}, valid_session
        assigns(:clowd).should eq(clowd)
      end

      it "re-renders the 'edit' template" do
        clowd = Clowd.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Clowd.any_instance.stub(:save).and_return(false)
        put :update, {:id => clowd.to_param, :clowd => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested clowd" do
      clowd = Clowd.create! valid_attributes
      expect {
        delete :destroy, {:id => clowd.to_param}, valid_session
      }.to change(Clowd, :count).by(-1)
    end

    it "redirects to the clowds list" do
      clowd = Clowd.create! valid_attributes
      delete :destroy, {:id => clowd.to_param}, valid_session
      response.should redirect_to(clowds_url)
    end
  end

end
